# Generated by Django 4.2.5 on 2023-09-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CLient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('chat_id', models.CharField(max_length=100, unique=True)),
                ('token_api', models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
    ]
