# Generated by Django 4.2.5 on 2023-09-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='chat_id',
            field=models.CharField(max_length=100),
        ),
    ]
